#!/usr/bin/env bash
#setting up load balancing
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get install haproxy=2.6.\*

sudo sed -i "s/ENABLED=0/ENABLED=1/g" /etc/default/haproxy
sudo sed -i "\$ a\listen 4826-lb-01\n\tbind *:80\n\tmode http\n\tstats enable\n\tbalance roundrobin\n\tserver 4826-web-01 52.91.59.143:80 check\n\tserver 4826-web-02 54.90.160.55:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
