#!/usr/bin/env bash
#setting up load balancing
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get install haproxy=2.6.\*

sudo sed -i "s/ENABLED=0/ENABLED=1/g" /etc/default/haproxy

sudo echo "listen 1489-lb-01" >> /etc/haproxy/haproxy.cfg
sudo echo "	bind 0:80" >> /etc/haproxy/haproxy.cfg
sudo echo "	mode http" >> /etc/haproxy/haproxy.cfg
sudo echo "	stats enable" >> /etc/haproxy/haproxy.cfg
sudo echo "	balance roundrobin" >> /etc/haproxy/haproxy.cfg
sudo echo "	option httpclose" >> /etc/haproxy/haproxy.cfg
sudo echo "	option forwardfor" >> /etc/haproxy/haproxy.cfg
sudo echo "	server 4826-web-01 52.91.59.143  check port 80" >> /etc/haproxy/haproxy.cfg
sudo echo "	server 4826-web-02 54.90.160.55 check port 80" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
