#!/usr/bin/env bash
#setting up load balancing
sudo apt-get update
sudo apt-get install -y haproxy
echo ENABLED=1 | sudo tee /etc/default/haproxy

sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

file=/etc/haproxy/haproxy.cfg

sudo cp $file $file.copy

sudo sed -i -e '$a\listen appname 0.0.0.0:80\n\tmode http\n\tstats enable' $file
sudo sed -i -e '$a\\tbalance roundrobin\n\toption httpclose\n\toption forwardfor' $file
sudo sed -i -e '$a\\tserver 4826-web-01 52.91.59.143:80\n\tserver 4826-web-02 54.90.160.55:80' $file

sudo service haproxy start
