#!/usr/bin/env bash
#transfering file through ssh tunneling
if [ $# -gt 3 ]
then
    scp -i $4 -o StrictHostKeyChecking=no  $3@$2:~/$1  /home/
else
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
fi
