#!/usr/bin/env bash
sudo apt-get update
sudo apt-get install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx restart
sudo echo 'Holberton School for the win!' > /var/www/html/index.nginx-debian.html

