#!/usr/bin/env bash
#setting up nginx server
sudo apt-get update
sudo apt-get install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo 'Holberton School' > /usr/share/nginx/html/index.html
sudo service nginx start
